### ISSUE TITLE
Fiat-Shamir

### ISSUE THREAD

**Issue by arifiorino** [uiuc-kang-lab/zk-torch#13]
Currently, the prover and verifier have a shared `Rng` that they use to generate the random values in the proofs. This `Rng` should be seeded with a cryptographic hash of the public values, in order to implement the Fiat-Shamir heuristic.

**Comment by ddkang** [comment]
Does arkworks have a transcript object we can use?

**Comment by liliatangxy** [comment]
https://github.com/arkworks-rs/spartan seems to use [merlin](https://docs.rs/merlin/latest/merlin/) for transcripts

Some of the proving systems in arkworks have their own Fiat Shamir rng implementations that could be general enough to use without using the proving system: https://github.com/arkworks-rs/marlin/blob/master/src/rng.rs
