### ISSUE TITLE
Layer component required

### ISSUE THREAD

**Issue by Vimalakirti** [uiuc-kang-lab/zk-torch#21]
It will be good to have layer components to group basicblocks into subgraphs and play with tensor shapes (e.g., reducing one dimension, reshape, ...).

Besides, it'll be good to map each onnx operation into the corresponding layer component in this repo since it will help us to easily convert onnx files.

**Comment by Vimalakirti** [comment]
In my opinion, a layer component will have the following I/O during initialization  

- Inputs:
    - tensors: `Vec<&ArrayD<Fr>>` // they might be input data, intermediate results, or model weights
    - basicblock_config: `BasicBlockConfig`
        - this struct includes “scale_factor” and other basicblock-related parameters (e.g., the “l” in matmul basicblock) 
    - layer_config: LayerConfig // this struct includes  	 
        - layer_type: `LayerType` (e.g., an enumerator to specify nonlinear layers, shape layers or others)  
        - layer_params: `Vec<i64>` // specify the parameters of the layer (e.g., which axes to reduce in ReduceSum layer)
        - input_shapes: `Vec<Vec<usize>>`
        - output_shapes: `Vec<Vec<usize>>`
        - mask: `Vec<i64>`
        - implementaion_idx: `usize` (we may want to do ablation studies on different implementations of the same layer)
- Outputs:
    - basicblocks: `Vec<Box<dyn BasicBlock>>` // crypto. components in the layer subgraph
    - nodes: `Vec<Node>` // each Node includes “which basicblock this node uses” and “its input indices (previous nodes)”
    - model_weights: `Vec<&ArrayD<Fr>>` // the model weights 

These outputs can then directly be used in our `Graph`.

**Comment by Vimalakirti** [comment]
Below is the updated version for layer I/O. 
- Summary:
    - `BasicBlockConfig` is dropped
    - `layer_params` can be HashMap
    - `input_shapes` and `output_shapes` can be included in `layer_params` for ML shape operations
    - `mask` is dropped

- Inputs (ML layer info. from ONNX file):
    - tensors: `Vec<&ArrayD<Fr>>` // they might be input data, intermediate results from previous layers, or model weights of the layer
    - layer_config: `LayerConfig` // this struct includes  	 
        - layer_type: `LayerType` (e.g., an enumerator to specify nonlinear layers, shape layers or others)  
        - layer_params: `HashMap<String, ArrayD<i32>>` // specify the parameters of the layer (e.g., {"axes": 1} or {"input_shape": [4, 16], ""output_shape": [32, 2, 1]})
        - implementaion_idx: `usize` (we may want to do ablation studies on different implementations of the same layer)
- Outputs (data for building the subgraph):
    - basicblocks: `Vec<Box<dyn BasicBlock>>` // crypto. components in the layer subgraph
    - nodes: `Vec<Node>` // each Node includes “which basicblock this node uses” and “its input indices (previous nodes)”
    - model_weights: `Vec<&ArrayD<Fr>>` // the model weights

**Comment by arifiorino** [comment]
This has been aded in #35.
