### ISSUE TITLE
Missing blinding and optimizations in copy constraint

### ISSUE THREAD

**Issue by liliatangxy** [uiuc-kang-lab/zk-torch#45]
#40 introduced copy constraints that are currently insecure due to missing blinding factors. 
We can also batch the pairings with quotients at the end.

**Comment by liliatangxy** [comment]
To completely fix the issue, it requires us to make changes to the Data and DataEnc constructors to address this case. As a workaround we can pass the correct blinding to the verifier so that we can support a validly blinded copy constraint, but to make it fully secure we need to support opening blinding in the `Data`/`DataEnc::new` paths.

**Comment by ddkang** [comment]
> To completely fix the issue, it requires us to make changes to the Data and DataEnc constructors to address this case. As a workaround we can pass the correct blinding to the verifier so that we can support a validly blinded copy constraint, but to make it fully secure we need to support opening blinding in the `Data`/`DataEnc::new` paths.

Comment it in code

**Comment by liliatangxy** [comment]
Closed with #47
